### ISSUE TITLE
数据库版本不兼容

### ISSUE THREAD

**Issue by TopGuo** [maoqyhz/MIMS#1]
很感谢您的分享，但是数据库附加会出现兼容性问题，建议：直接生成sql脚本，放到一个文件夹里，这样，其他人看到后，无论用的是sql 05，08，12 ...等都不会报错了！

**Comment by maoqyhz** [comment]
的确是这样，但是现在电脑上已经没有sql server2012了，所以无法生成sql脚本了，抱歉。

**Comment by TopGuo** [comment]
好吧，很遗憾了！
